[package]
name = "make_boards"
version = "0.1.0"
authors = ["Andrew-Schwartz <andrewschwartz59@gmail.com>"]
edition = "2018"

[dependencies]
tiny-skia = "0.3.0"
image = "0.23.12"
itertools = "0.10.0"
rayon = "1.5.0"