[package]
name = "command_data_derive"
version = "0.1.0"
authors = ["Andrew-Schwartz <andrewschwartz59@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.8"
proc-macro2 = "1.0.24"

[dependencies.syn]
version = "1.0.58"
features = ["extra-traits", "derive"]